### PR TITLE
Add Implemented Endpoints to README

### PR DESCRIPTION
**Pull request by SvenJanssens**
Add Implemented Endpoints to README - Issue #94

### CODE REVIEW

**Comment by SvenJanssens** [comment]
Hi,
I have created the PR. Not sure who are usually the reviewers, so I have assigned @sssilver and @nickvollmar (as I saw the same reviewers were also assigned to previous PRs).
Thanks a lot in advance and have a nice day!
Regards,
Sven

**Comment by ashleymichal** [comment]
wow this is exhaustive, well done! while i appreciate the utility, i am not confident this will be well maintained, or as useful as it could be; i think it would be easier/less noisy to either list what we DO implement, or somehow script a way to show what we do/don't implement. that's my two cents anyway.

**Comment by SvenJanssens** [comment]
I actually made the complete list to make it easier to maintain. As for now we can just put the X between the brackets to mark something as implemented. While if it just lists the endpoints implemented, then more effort is needed, causing more friction and so it becomes less likely for it to get maintained. A script would be even better, but I am not at home with writing one.
If it would create too much noise on the readme, then I don't mind just keeping it as an overview for myself on my branch. Should I close the pull request?

**Comment by SvenJanssens** [comment]
Hmm, looks like I messed up the pull request by updating the branch with the latest changes. So I will close it. Sorry for the troubles.

**Comment by ashleymichal** [comment]
i don't think you need to close it, i think others  should chime in as well. i'm only one voice and  the utility is helpful for sure.

**Pull request closed without merging**
